# Generated by Django 5.1.6 on 2025-04-27 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_article_city_article_pokemon_advertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('dislikes', models.JSONField(blank=True, default=list)),
                ('subscriptions', models.JSONField(blank=True, default=list)),
                ('notify_setting', models.CharField(choices=[('all', 'All Articles'), ('subscription', 'Subscribed Topics Only'), ('favorite', 'Favorite Editors Only'), ('none', 'No Notifications')], default='subscription', max_length=50)),
                ('favorite_editors', models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
