# Generated by Django 5.1.6 on 2025-04-27 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_notification_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
