# Generated by Django 5.1.6 on 2025-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_remove_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dislikes',
            new_name='disliked_topics',
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_editors',
            field=models.ManyToManyField(blank=True, to='news_app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_setting',
            field=models.CharField(default='daily', max_length=20),
        ),
    ]
