# Generated by Django 5.1.6 on 2025-05-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_tag_creator_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorite_editors',
            new_name='favorite_creators',
        ),
    ]
